name: Check packages

on:
  push:
    paths:
      - 'packages/**'

jobs:
  run-npm-bootstrap:
    name: 'Run npm bootstrap in modified package'
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run npm bootstrap
        run: npm run bootstrap
        env:
          USE_GIT_HTTP_ENDPOINTS: 'true'
